version: "3.8"

services:
  mortgage-calc:
    container_name: mortgage-calc
    build: .
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: "/configs/config.yaml"
    volumes:
      - ./configs:/configs
    restart: unless-stopped
